### ISSUE TITLE
RFC: restructure this project to use a single package mgt

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.React.Common#154]
## Is your feature request related to a problem?
Yes. Every single component has it's own package management which results in astronomic download times when packages are restored and over 3Gb of mostly duplicate packages.

## Describe the solution you'd like
Restructure this project so it uses a single point for this.

## Additional context
The original idea was to have individual components that people could leverage in their code as individual components. The only place this is currently used is in the personabar where *all* components are loaded. Nulling this original idea. So the question is: should we not go even further and build to a single js file (like the AdminExperience project does to export-bundle.js)?

Let us know what you think.

**Comment by tpluscode** [comment]
> So the question is: should we not go even further and build to a single js file (like the AdminExperience project does to export-bundle.js)?

Don't think so. The problem is not with publishing but with managing dev space.

Have a look at https://lernajs.io. It let's one manage a single `node_modules` folder and also keeps track of internal dependencies between packages. In other words, you publish them independently and define dependencies in `package.json` but during development those dependencies will be resolved from local folders and not npmjs.org.

**Comment by ohine** [comment]
I think setting up [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) first might make the most sense. It seems like it'll solve our short term issues and great reduce the build times. Whatever we do for React.Common also needs to be applied to AdminExperience as they both have the exact same issue with duplicate dependent packages.

**Comment by donker** [comment]
> 
> 
> > So the question is: should we not go even further and build to a single js file (like the AdminExperience project does to export-bundle.js)?
> 
> Don't think so. The problem is not with publishing but with managing dev space.

OK. Yes, you're right. I was just thinking out loud because from what I can tell we don't use these components individually and it just increases complexity. But it's not an urgent issue.

**Comment by mtrutledge** [comment]
yarn workspaces has some issues with this particular project structure and inner dependencies. Even with yarn workspaces, my yarn cache just for these sets of projects ended up to be 12 gigs and it still took hours to get the components with a clear cache and build.

Instead of attempting a mono repo pattern here it makes much more sense to create a single package that you reference the components from. There really is not a difference between our component project and something like React bootstrap. It is just a package of components you can use in your project. The webpack and dev tooling take care of any packaging issues and the components would not be packaged with the final build for the packages or any project using the components because dnn-webpack-externals defines them as being external. The persona bar is responsible for loading all these components. There is a downside to this, it means that these React components cannot be used outside the Persona Bar unless you load the external bundle yourself.

If you are using the React Common library you are creating a Persona Bar module. This currently requires you to reference, at a minimum, 9 components form Dnn.React.Common to get your project going (Page Header, Page, Page Body, Label, Text Box, Webpack externals, Dnn Global Style, Svg Icons, and Dnn eslint config)

There are also quite a few interdependencies between the components in this project, further pushing us to a single package. The changes to any existing projects would be minimal. In fact, it would require two changes:

1) Update package.json to remove the individual components and add the single package
2) Change your import statements in your component from individual line items to `import {dnn-label, dnn-textbox} from dnn-react-common;`

I am willing to work on the project re-structure. I have been talking about it for some time in the TAG group.

**Comment by donker** [comment]
After a brief discussion in the TAG team there is consensus that this is a high priority item and we should move ahead as Matt outlined above. I'm closing this RFC and creating a regular issue out of this.
